apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lease-configurations.spheron.network
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: spheron.network
  scope: Namespaced
  names:
    plural: lease-configurations
    singular: lease-configuration
    kind: LeaseConfiguration
    shortNames:
      - lcs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - lease_id
                - manifest
                - execution_environment_config
              properties:
                lease_id:
                  type: integer
                  format: uint64
                manifest:
                  type: string
                  description: JSON-encoded manifest
                execution_environment_config:
                  type: string
                  description: JSON-encoded runtime options (ExecutionEnvironmentConfig)

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-monitor-sa
  namespace: spheron-services
  labels:
    "spheron.network": "true"
    "app.kubernetes.io/name": "node-monitor"

---

apiVersion: v1
kind: Namespace
metadata:
  name: spheron-lease-configurations