apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spheron-provider-admin
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: spheron-provider
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
