{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spheron-provider
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: spheron-provider
    spheron.network: 'true'
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
