apiVersion: v1
kind: Service
metadata:
  name: spheron-provider
  namespace: {{ .Release.Namespace }}
  labels:
    spheron.network: "true"
    app.kubernetes.io/name: spheron
spec:
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 8443
      targetPort: api
  selector:
    app.kubernetes.io/name: spheron-provider
    spheron.network: "true"
